### ISSUE TITLE
Add feature to ignore first line

### ISSUE THREAD

**Issue by malenkiki** [jillix/a-csv#13]
Sometimes, I must deal with CSV having header row (name to each column). It may be very interesting to have an option to allow skipping first line.

What do you think about that?

**Comment by IonicaBizau** [comment]
That's a good idea for handling the first line. :sparkles: 

Until this is implemented, the easy solution to handle this is by checking the first line this way:

```js
var CSV = require("a-csv");
var file = "test.csv";
var options = {
    delimiter: ";",
    charset: "win1250"
};

var headers = null;

CSV.parse(file, options, function (err, row, next) {

    if (err) {
        return console.log(err);
    }
    
    if (row === null) {
        return; // finished
    }
    
    if (!headers) {
       headers = row;
       return next();
    }

    next();
});
```

/cc @adioo

**Comment by malenkiki** [comment]
Great, thank you for this solution!

I hope use the new feature soon ;-)

**Comment by IonicaBizau** [comment]
Using `a-csv@2.0.0` you can do:

```js
var CSV = require("a-csv");

CSV.parse("path/to/file.csv", { headers: true }, function (err, row, next) {

    if (err) {
        return console.log(err);
    }

    if (row === null) {
        return; // finished
    }

    next();
});
``` 

Using `headers:true`, the first line will be ignored. :sparkle:

**Comment by IonicaBizau** [comment]
:ship: `2.0.0`, so be happy! :smile: :sparkles:

**Comment by malenkiki** [comment]
Great! I will use it as soon as possible ;-)
